version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - lakehouse-network
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./data/trino_data/catalog:/etc/trino/catalog
    networks:
      - lakehouse-network
  postgres-nessie:
    image: postgres:latest
    container_name: postgres-nessie
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nessie
    networks:
      - lakehouse-network
    volumes:
      - ./data/postgres_nessie_data:/var/lib/postgresql/data
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - NESSIE_SERVER_TYPE=standalone
      - NESSIE_STORAGE_BACKEND=postgres
      - NESSIE_STORAGE_POSTGRES_HOST=postgres-nessie
      - NESSIE_STORAGE_POSTGRES_PORT=5432
      - NESSIE_STORAGE_POSTGRES_USER=admin
      - NESSIE_STORAGE_POSTGRES_PASSWORD=admin
      - NESSIE_STORAGE_POSTGRES_DBNAME=nessie
    depends_on:
      - postgres-nessie
    networks:
      - lakehouse-network
  
  postgres-metabase:
    image: postgres:latest
    container_name: postgres-metabase
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=metabase
    volumes:
      - ./data/postgres_metabase_data:/var/lib/postgresql/data
    networks:
      - lakehouse-network
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=postgres-metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=admin
      - MB_DB_PASS=admin
      - MB_DB_DBNAME=metabase
    depends_on:
      - postgres-metabase
    networks:
      - lakehouse-network
networks:
  lakehouse-network:
    driver: bridge
